version: '3'
services:
  node:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: ${USER_ID}:${GROUP_ID}
    tty: true