version: '3'
services:
  node:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./app:/usr/src/app
      - ./imadoki-nextjs:/usr/src/imadoki-nextjs
    privileged: true
    tty: true